"""empty message

Revision ID: 843d29a78b03
Revises: 95b001dd67be
Create Date: 2023-11-04 10:40:55.413318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843d29a78b03'
down_revision = '95b001dd67be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    # ### end Alembic commands ###
