"""empty message

Revision ID: 85afd5ee6d87
Revises: f4f28eed705e
Create Date: 2023-08-06 11:05:22.632178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85afd5ee6d87'
down_revision = 'f4f28eed705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    # ### end Alembic commands ###
